name: run-tests

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16', '1.14' ]
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Test
      run: go test -v ./...
