name: run-tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.16', '1.14' ]

    name: Run tests [Go ${{ matrix.go }}]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Test
      - run: go test -v ./...
